modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="explorassist"
version="1.0.0"
displayName="Explorer Assist"
description="Personal exploration assistant."

[[dependencies.explorassist]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.explorassist]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="SERVER"
